
POST http://localhost:3000/api/projects
Content-Type: application/json

{
  "title": "Awesome Seed Project 1",
  "shortDescription": "Created via seeding script 1",
  "longDescription": "This is a full description of the project 1",
  "voyage": 55,
  "tier": 3,
  "mainImageUrl": "https://image.com",
  "githubRepo": "https://github.com/example/awesome-project",
  "teammates": [3,4,5],
  "tags": [1]
}
###
GET http://localhost:3000/api/projects/search/teammates?search=@
Content-Type: application/json
